# Generated by Django 5.0.4 on 2024-06-12 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('Knoxx Alumni', 'Knoxx Alumni'), ('Knoxx Academic Staff', 'Knoxx Academic Staff'), ('Knoxx Non-Academic Staff', 'Knoxx Non-Academic Staff'), ('Knoxx Student', 'Knoxx Student')], max_length=50)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('testifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
